jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/tests-cookbook.py

Adds AESGCMKW, PBES2 and ECDH-ES algorithms with tests.
@npmccallum can you please take a look ?

Add the missing JWE Key wrapping algorithms

---

jwcrypto/jwe.py
jwcrypto/tests-cookbook.py

@npmccallum check if this is good enough

Allow both a key or a password for Pbes2

---

jwcrypto/common.py
jwcrypto/jwk.py
jwcrypto/tests.py

This is pretty straightforward @npmccallum let me know what you think

Jwk thumbprint

---

MANIFEST.in

Signed-off-by: Christian Heimes <cheimes@redhat.com>

Include tox.ini and setup.cfg in sdist

---

.travis.yml
setup.py
tox.ini

Signed-off-by: Christian Heimes <cheimes@redhat.com>

Support and test with Python 3.6

---

jwcrypto/jwt.py

Just fixing `jwcrypt`->`jwcrypto` in the docs

Fix minor typo

---

jwcrypto/common.py
jwcrypto/jwa.py
jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

Make all exception derive from JWException

---

docs/source/jwe.rst

Just add a quick example on how to use asymmetric keys with JWE tokens.

Add example of encrypting/decrypting using asymmetric keys

---

jwcrypto/jwe.py
jwcrypto/tests.py

Better validation of JWE compact serialization

---

Makefile
jwcrypto/jwa.py

Rfc6979 to dss

---

jwcrypto/jwk.py
jwcrypto/tests.py

Validate key parameters on import

---

jwcrypto/jwk.py

This uses more idiomatic types to handle internal structured data

Rework internal JWK structures for clarity

---

jwcrypto/jwa.py

Stop using our own, pyca has has AES Key wrap support for long enough
now.
Resolves #137

Use python-cryptography's AES key wrapping

---

jwcrypto/jwa.py
jwcrypto/tests.py

Fix case where CEK is greater in size than KEK in ECDH-ES

---

jwcrypto/jwk.py
jwcrypto/tests.py

import_keyset no longer returns self.
Another alternative of https://github.com/latchset/jwcrypto/pull/131

Fix JWK.from_json #130

---

jwcrypto/jwt.py
jwcrypto/tests.py

Instead of refusing to deserialize a JWT when there is no kid and we are
given a Key Set, try all keys and see if one works.
Fixes #143

Allow to use JWKSet on a JWT with no KID

---

jwcrypto/jwk.py

Fix travis build error from pep8 failure.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

b64U -> b64u for pep8

---

jwcrypto/jwe.py

Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Fixed JWE jose_header

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/tests.py

Adds X25519 and X448 ECDH-ES exchange support
Fixes #127

Complete Rfc 8037 support

---

jwcrypto/jwk.py

According to RFC 7518 6.2.1.2 the Coordinates need to be encoded such
that the size of the encoded string is fixed (based on private curve
key_size). Fix _encode_int to take in account the bit_size given
python-cryptography gives us python integers and that may lead to
truncation of leading zeros when doing the conversion via hex().
Fixes: #158

Fix encoding length of EC keys Coordinates

---

jwcrypto/jwk.py

This crept in unseen during the work to add ed448
Fixes #161

Remove unwanted debug print

---

tox.ini

Try to fix travis issues with the sphinx target

Remove cap on sphinx version

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

This is as per
- https://tools.ietf.org/html/draft-ietf-cose-webauthn-algorithms
- https://mailarchive.ietf.org/arch/msg/cose/91MouVA43DefbpQOB7l5daCEeIc

Add secp256k1 EC Key curve support

---

jwcrypto/jwk.py
jwcrypto/tests.py

This allows to avoid json_decoding again to manipulate the exported
data.
Fixes #28

Add method to export Keys ans Sets as dictionaries

---

jwcrypto/jwt.py

Small change to get tox happy.

Rename ambiguous variable

---

jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/tests.py

Add ES256K to the Default allowed algorithm
- https://www.rfc-editor.org/rfc/rfc8812.html

RFC 8812 - Add Default allowed algorithms

---

.travis.yml
Makefile
jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/jwt.py
jwcrypto/tests.py
setup.py
tox.ini

This PR changes JWK to inherit from dict, and behave like a dictionary
Fixes #27

Turn JWK into a dict-like object

---

README.md

I had to dig around to figure out how to install it.

Installation instructions + extra badges

---

jwcrypto/jws.py
jwcrypto/tests.py

Apparently Let's Encrypt's ACME Server accepts JWT tokens that are JWS
tokens with an empty payload.
Fixes #224

Allow empty payloads in JWS tokens

---

jwcrypto/common.py
tox.ini

Suppress lint and pep8 errors

---

.github/workflows/build.yml
jwcrypto/tests.py

Sounds like some caching is preventing builds as older packages are not found (index and repo are not in sync). Try an update to see if we can fix this.

Try to apt-get update before build

---

jwcrypto/jws.py
jwcrypto/tests.py

Add way to verify detached payloads

---

jwcrypto/tests.py

Otherwise false negatives may happen

Fix test to use correct parameters

---

jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py

Add docstrings for return types of public methods

---

setup.py

Raising the bar for minimum pyca/cryptography

---

.github/workflows/build.yml
tox.ini

avoid introducing mispelt words in future PRs

Add codespell checks in CI

---

.github/workflows/build.yml
jwcrypto/jwa.py
jwcrypto/jws.py
jwcrypto/tests.py

As infrastructure changes we need to fix issues CI experience, or old problems the tools find only now.

Fix  assorted CI issue

---

.readthedocs.yaml

Read the Docs now requires a config file

---

.github/workflows/publish-to-pypi.yml

First attempt to fix #326 failed.
Try again.

Fix pypi publishing

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/ppc64le.yml

A few show deprecation warnigns, do a general refresh and update

Update CI actions
