jwcrypto/jwt.py

If self.claims is setted before `self._reg_claims`, then `self._add_default_claims` will never do its job in the  `__init__` code : 
```python
@claims.setter
def claims(self, c):
if isinstance(c, dict):
self._add_default_claims(c)
self._claims = json_encode(c)
else:
self._claims = c
```
```python
def _add_default_claims(self, claims):
if self._reg_claims is None:
return
...
```
By setting `self.claims` after `self._reg_claims`, it should be OK.
Current workaround is to initialize the token with claims=None and default_claims (!= None), and then set the claims, which is a little counter-inituitive (I have to check the code several times to understand why the default claims were not setted as expected).

Set claims after reg_claims

---

jwcrypto/jwk.py

This pull request fixes a minor typo in the `jwcrypto.jwk.JWK` docstrings.

Fix typo in jwk chapter of docs

---

jwcrypto/jwa.py
setup.py

Use sign() and verify() directly instead.
This will Fix also latchset/custodia PRs, which are now failing on pyca deprecation warnings.

Cyrptography deprecated signer and verifier

---

jwcrypto/jwe.py
tox.ini

In Python 3, '' != b''. With bytes warning enabled, comparison of bytes and str raise an exception, too.
Remove unnecessary calls to str()
json_decode() returns str instances for str values anyway. In case the JSON payload contains invalid types, base64 codec will fail with an appropriate error message.
'some.string'.split('.') returns a list of str.

Fix bytes comparison

---

jwcrypto/jwt.py
jwcrypto/tests.py

If the claim passed was not one of sub, aud, iat, etc. then passing a string as a value to check_claims would raise an error if it was not an integer

Fix error interpolation on nonstandard jwt claims

---

jwcrypto/jwk.py
jwcrypto/tests.py

This makes it simpler to get a JWK that contains excluively a pulic
key from an existing JWK. It fails if no public key is available in
the source JWK.
Only known public elements are returned. "Unknown" attributes are
not copied over.
Resolves #99

Add function to get a public only JWK

---

jwcrypto/tests.py

Change one test to also test using strings instead of dicts as headers.
This is supported in the code but was not tested.
Closes #96

Test header using string not dict

---

jwcrypto/jwt.py

If the 'aud' value was wrong in a jwt, then the error messages was a bit wrong. For example, if we expected the audience to be one of `["abc.com", "123.com"]` but we gave it `"www.google.com"`, then the error message would say `Expected ["abc.com", "123.com"] in "www.google.com"` which is the wrong way round.
This just makes it to the error message prints out those things in the right order.

Fix misleading aud mismatch error message

---

jwcrypto/jwa.py

There was a typo in the "_EcdhEsAes256Kw" class. I have changed "A128KW" in the description for the class to become "A256KW" in accordance with the algorithm.

Fixing "A128KW" under "_EcdhEsAes256Kw"

---

jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

Together with non encoded payloads this commit also adds sull support
for dealing with detached payloads on deserlization and serialization.
The payload must still be provided for any computation, but can be
removed before serialization and add after deserialization of a JWS with
detached payload.
Fixes #4

Add support for RFC7797

---

jwcrypto/common.py
jwcrypto/jwe.py
jwcrypto/jws.py
jwcrypto/tests.py

Create a way to extend the functionality with custom header checking without adding dependencies into the main library, as discussed in #146 
Current implementation only takes in `JWSEHeaderParameter`, but it can be extendable to any kind of header parameter (like JWK) if we take in a set of validation functions that tells us if a header can be ovewritten, and how to reference the `check_fn`. Would like to get some feedback on this.
Side note: Took the opportunity to merge the HeaderParameter types of JWE and JWS (according to RFC 7515 - 9.1).

Create extendable HeaderRegistry 

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/tests.py

Support for Ed25519 and Ed448, allowing signing and verification.
Some code cherry-picked from [Simo5's rfc8037 branch](https://github.com/simo5/jwcrypto/tree/rfc8037).

RFC 8037 - Support for Ed25519, Ed448

---

jwcrypto/jwa.py
jwcrypto/tests.py
tox.ini

Apparently this is required by OpenID Connect as an option:
https://openid.net/specs/openid-connect-core-1_0.html#RequestObject
In order to avoid accidental use of the None algoritm, which is disabled
by default but easy to casually enable, add the requirement to pass a
"None Key".
The none key clearly indicates that the user really wants to allow the
'none' algorithm to be used.
The "None Key" is an 'oct' key with key size of 0.
Example:
```
>>> from jwcrypto import jwk,jwt
>>> e="eyJhbGciOiJub25lIn0.eyJpc3MiOiJqb2UiLCJodHRwOi8vZXhhbXBsZS5jb20vaXNfcm9vdCI6dHJ1ZX0."
>>> k=jwk.JWK(generate='oct', size=0)
>>> E=jwt.JWT(algs=['none'])
>>> E.deserialize(jwt=e, key=k)
>>> E.claims
u'{"iss":"joe","http://example.com/is_root":true}'
```
Fixes #163

Add the ability to verify 'none' signatures.

---

jwcrypto/common.py

Import ABC from collections.abc instead of collections for Python 3.9 compatibility

---

jwcrypto/jwk.py
jwcrypto/tests.py

Do not require a crv param to be passed we have enoug info on our own.
Fixes #176

Derive okp key type on import

---

README.md
docs/source/jwk.rst
docs/source/jwt.rst
jwcrypto/common.py
jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

Reading through the docs I found a few typos so I was hoping this might be helpful.

Fix some documentation typos

---

jwcrypto/jwt.py
jwcrypto/tests.py

Nowhere in the spec it says the payload must not be an empty dictionary.
It makes little sense to not have any claims, because then, what do you
claim? But that's a problem for the user, especially given the fact you
could already pas in the literal string '{}' and it would get signed.
However a completely empty string is invalid, at least one character,
even just a space is needed.
Fixes #187

Make sure an empty dict is a valid JWT payload

---

README.md
jwcrypto/jwe.py
jwcrypto/jwt.py
jwcrypto/tests-cookbook.py
jwcrypto/tests.py

RSA1_5 relies on the PKCS1 v 1.5 padding algorithm.
This algorithm has been shown time and again to be very difficult to
implement correctly because it requires a fully constant time
implementation including in application level error handling.
Python Cryptography which is our crypto engine documents that the
current API is not contacnt time.
This patch deprecates the algorithm and removes it from the default
allowed algorithms list. This means that code need to be changed in
order to explicitly allow RSA1_5 going forward.
Resolves #193

Deprecate RSA1_5 and remove from defaults

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/tests.py

PBES2 accepts only a plaintext password or bytes which is different
from all other algorithms. Make it support passing in a symmetric key,
and add a jwk classmethod to create a symmetric key from a password.
Resolves #196

Make PBES2 behave like all other algorithms

---

jwcrypto/jws.py

As RFC 7515 Sections 7.10 states the compact serialization must carry
the algorithm in the protected header. Make sure we do not produce a
compact serialization without that.
Fixes: #198

Enforce protected header in compact serilization

---

setup.py

Six is used as a direct import here: https://github.com/latchset/jwcrypto/blob/master/jwcrypto/jwt.py#L6
But it was not listed as a dependency in the setup.py. Because six is also a dependency of tox the tests didn't fail. When jwcrypto is used as a dependency the system does fails though.
This previously went unnoticed probably because cryptography also had six as a dependency.

Added six as a dependency to avoid import error

---

.travis.yml
tox.ini

Not always needed but some images build it.

Add Rust in travis so we can build cryptography

---

jwcrypto/jwk.py
jwcrypto/tests.py

This same issue was already handled for private keys, but somehow it was
mishandled in public keys.
Fixes #204

Fix importing Public EC keys from PEM files

---

jwcrypto/jwk.py
jwcrypto/jwt.py
jwcrypto/tests.py
tox.ini

Fix crash in Keyset JWT decoding exception handler

---

jwcrypto/jwk.py

Note that this was not an issue before #210 because the hidden dict would not leak via repr.
Now that JWK avoids using a hidden dict we need to deal with accidentally leaking of secret key material via a repr used in some debugging function.
Keys can always be exported via .export() of course, but that is not something that could be accidentally done by other tools that try to helpfully debug issues.

Add __repr__ functions for JWK and JWKSet

---

setup.py

This should fix #228 
See: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

Set python requirement to 3.6+ in setup.py

---

jwcrypto/jwa.py
jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

I'm not sure if the object-commit really adds any value. You can delete it, if desired. There's no speed difference, unlike the `{}` and `[]` replacements.

Use list/dict literals instead

---

jwcrypto/jwt.py
jwcrypto/tests.py

Issue #239 brought up that check_claims are not actually checked to be
of the right type and this can lead to confusion in some case, as well
as defer error reporting after potentially costly signature
computations.
Check for general claims type validity upfront where appropriate.
Resolves #239

Check provided claims for type correctness

---

jwcrypto/jwa.py

JWE does not define any algorithm to asymmetrically encrypt content
direcly. Instead, algorithms like RSA-OAEP-256 wrap an AES key which is
then used to symmetrically encrypt the content.
This fixes a bug where JWE decryption fails with JWKs with `key_ops: ["unwrapKey"]`. 
Section 4.3 of RFC 7517 defines the `unwrapKey` operation as "decrypt
key and validate decryption, if applicable" which is exactly what RSA
keys are used for in algorithms like RSA-OAEP-256.
see https://datatracker.ietf.org/doc/html/rfc7517#section-4.3

Fix key_op in get_op_key for RSA unwrap operation

---

jwcrypto/jwk.py

Pyca rightfully performs consistency checks when importing keys and
these operations are rather expensive. So cache keys once generated so
that repeated uses of the same JWK do not incur undue cost of reloading
the keys from scratch for each subsequent operation.
with a simple test by hand:
$ python
>>> from jwcrypto import jwk
>>> def test():
...     key = jwk.JWK.generate(kty='RSA', size=2048)
...     for i in range(1000):
...             k = key._get_private_key()
...
>>> import timeit
Before the patch:
>>> print(timeit.timeit("test()", setup="from __main__ import test", number=10))
35.80328264506534
After the patch:
>>> print(timeit.timeit("test()", setup="from __main__ import test", number=10))
0.9109518649056554
Resolves #243

Cache pub/pri keys on retrieval

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/tests.py

Add P-256K alias for secp256k1

---

.github/workflows/build.yml
Makefile
docs/source/conf.py
docs/source/index.rst
docs/source/jwe.rst
docs/source/jwk.rst
docs/source/jws.rst
docs/source/jwt.rst
tox.ini

Reformat example code as necessary to make it pass tests.
Specifically some of the randomly generated output has been replaced
with '...' which is the only way to make doctest match/skip a part of
the ouput while still running the command for testing.
Resolves #102

Add a sphinx doctest target

---

jwcrypto/jwk.py
jwcrypto/jwt.py
jwcrypto/tests.py

Well, crud. I accidentally close #266 it seems. Here is the description, for reference.
I recently ran into a case where token servers had unique keys but with duplicate `kid`s. Looking at the RFC, it has pretty loose requirements for `kid` and doesn't even require that `kid` be unique:
>[4.5](https://datatracker.ietf.org/doc/html/rfc7517#section-4.5).  "kid" (Key ID) Parameter
> 
>    The "kid" (key ID) parameter is used to match a specific key.  This is used, for instance, to choose among a set of keys within a JWK Set during key rollover.  The structure of the "kid" value is unspecified.  When "kid" values are used within a JWK Set, different keys within the JWK Set SHOULD use distinct "kid" values.  (One example in which different keys might use the same "kid" value is if they have …

handle keys with duplicate kids

---

setup.py

When Release scripts publish to PyPI they will set the README.md as
the long decription there.

Source README.md in setup to be used for PyPI

---

jwcrypto/jwa.py
jwcrypto/jwe.py
jwcrypto/tests.py

This was not really obvious but clearly it should be possible to pass in
parameters (p2s/p2c) in input when using PBES, and set defaults if they
are not provided.
Fixes #279

Allow passing p2s/p2c params on encrypting

---

jwcrypto/jwt.py
jwcrypto/tests.py

This means that if a server checking a token provides an array as the
check_claims argument it intends that the server is handling multiple
identities and the token checks will result valid as long as one of the
audiences matches one of the identities the server impersonates.
Fixes #277

Allow audience claims to be arrays

---

jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

In some cases (when a dict is passed instead of a json string) some operations would end up referencing the arguments directly and modifying them during processing.
Ensure arguments that may be stored and modified are actually copied in.
Fixes #281

Immutable args

---

jwcrypto/jwe.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

Implement beter representation for JWE, JWS, JWT objects

---

jwcrypto/jwt.py
jwcrypto/tests.py

This allows callers to deserialize() without a key and later validate the
parsed token without having to deserialize() again from scratch.

JWT: Add validate() method

---

jwcrypto/jwe.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

This finally allows to use JWKSets directly with JWE and JWS tokens and reduces the spamming of the decryoptlog/verifylog when a kid is provided in the headers and the keyset has the matching kid for a key.
Fixes #129

Move JWKSet processing from JWT into JWE and JWS directly

---

docs/source/common.rst
docs/source/index.rst
jwcrypto/jwk.py
jwcrypto/jws.py
tox.ini

Fix issues uncovered by sphinx nitpicking option

---

tox.ini

As builds started failing with latest Fedora/openssl try to see if it is
due to HW optimizations failing on the github runner.

Try to disable HW optimizations on ppc64le

---

docs/source/common.rst
jwcrypto/common.py
jwcrypto/jwe.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

This new Exception is returned only for the newly introduced support for
using JWKset.
This patch also includes a bugfix for jwe to be able to successfully
decrypt using a JWKSet, which was non-functional, and a direct test for
both JWE and JWS to insure no regressions in JWKSet support.
Also restores use of JWTMissingKey for backwards compatibility.
Fixes #291

Introduce a new JWKeyNotFound exception

---

docs/source/jwt.rst
jwcrypto/jwt.py
jwcrypto/tests.py

Note this fix technically breaks the current JWT api.
unfortunately there was no way to address this weakness without a change in semantics.
This means some applications may throw exceptions in some cases that were previously handled.
A knob to alter this behavior has been provided for applications that can't immediately refactor but still wants a way to upgrade t later jwcrypto releases.

Add fix for CVE-2022-3102

---

jwcrypto/jwt.py
jwcrypto/tests.py

These additional heuristics help in case the calling application was correctly calssifying key usage, as this is another valid hitn of what the application intended.
Invalid key usage would already cause failure, so this does not affect the countermeasures introduced but can avoid issues in older applications.

Add more heuristics for backwards JWT compat

---

jwcrypto/jwt.py
jwcrypto/tests.py

I just noticed that the test suite of a package I'm working on are suddenly failing. Short digging later, there was a typo in the newly released 1.4.1

Fix typo in new backwards JWT compat heuristics

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/tests-cookbook.py
jwcrypto/tests.py

[`codespell --ignore-words-list="ect,ser" -w .`](https://pypi.org/project/codespell/)

Fix typos with codespell

---

jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/tests.py

Hi,
this pull request adds the Brainpool curves support to jwcrypto. Since cryptography already supports the Brainpool curves,
it's more or less just a boilerplate code. I tried to add the test cases in your style too.
In Germany, especially in Healthcare we are obliged to use the Brainpool elliptic curves, additionally to NIST P-xxx. 
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03116/BSI-TR-03116-5.pdf?__blob=publicationFile&v=4
https://fachportal.gematik.de/fachportal-import/files/gemSpec_IDP_Dienst_V1.4.0.pdf

Add Brainpool EC-curves support

---

jwcrypto/jwt.py

The "claim is not a StringOrURI type" error message was not properly interpolated.

Fix error message

---

Makefile
jwcrypto/jwa.py
jwcrypto/jwk.py
jwcrypto/tests.py

Better support for algorithms that have different input keysize requirement

---

jwcrypto/jwk.py
jwcrypto/tests.py

This is a very small change to add the ability to import and export PEM X22519 keys.
I am not sure why the documentation build failed, the suggested solution (add a configuration) seems beyond the scope of this change.
The tests pass locally, for what it's worth:
<details>
<summary>Tox output</summary>
```
$ tox
.pkg: _optional_hooks> python /usr/local/python/3.10.8/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /usr/local/python/3.10.8/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /usr/local/python/3.10.8/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: …
```

Fix X22519 import/export from PEM

---

.gitignore
jwcrypto/jwa.py
jwcrypto/jwe.py
jwcrypto/jwk.py
jwcrypto/jws.py
jwcrypto/jwt.py
jwcrypto/tests.py

This PR represents an easy refactor of small parts of the source code where the PDB symbols was used for variable assignments. It simply removed the variable names `a`, `c` that are used in PDB to inspect the args and continue the execution.
Closes https://github.com/latchset/jwcrypto/issues/327#issuecomment-1686352603

chore: refactor for removing pdb symbols

---

jwcrypto/jwa.py
jwcrypto/tests.py

Unbounded p2c headers may be used to cause an application that accept PBES algorithms to spend alot of resources running PBKDF2 with a very high number of iterations.
Clamp the default maximum to 16384 (double the default of 8192). An application that wants to use more iterations will have to chenge the jwa default max.
Fixes CVE-2023-6681

Fix potential DoS issue with p2c header

---

jwcrypto/jwk.py
jwcrypto/jwt.py
setup.py

replace deprecated package with typing_extensions

---

.readthedocs.yaml
docs/requirements.txt

Missing requirements caused the build to fail to include autogenerated doc text.
Fixes #344

Fix doc generation

---

jwcrypto/jwe.py
jwcrypto/tests.py

Address potential DoS with high compression ratio

---

jwcrypto/jwk.py
jwcrypto/tests.py

This has some significant performance impact and
is ok to use with trusted keys.
The way to use it is to create or import a JWK, and then set the object property named unsafe_skip_rsa_key_validation to True
Fixes #353

Allow to pass through pem loading unsafe option

---

jwcrypto/jwt.py
jwcrypto/tests.py

Claim 'scope' is formally standardized by this RFC:
https://datatracker.ietf.org/doc/html/rfc8693#name-scope-scopes-claim
It's been in use for quite a while though and it's a part of standard token provided by Keycloak, which is a long time industry standard for access management.
Keycloak tokens may and quite often do contain multiple scopes, hence the need for this patch.

Add support for 'scope' claim with multiple scopes
